#include QMK_KEYBOARD_H


#define _BASE 0
#define _MOUSE 1
#define U_RDO KC_AGIN
#define U_PST KC_PSTE
#define U_CPY KC_COPY
#define U_CUT KC_CUT
#define U_UND KC_UNDO

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	//[_BASE] = LAYOUT(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LCTL, MT(MOD_LGUI, KC_A), MT(MOD_LALT, KC_S), MT(MOD_LSFT, KC_D), MT(MOD_LCTL, KC_F), KC_G, KC_LSPO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_GRV, KC_INS, KC_LEFT, KC_RGHT, KC_RGUI, KC_LALT, KC_HOME, KC_BSPC, KC_LALT, KC_END, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_SLCK, KC_PAUS, KC_NO, RESET, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_H, MT(MOD_RCTL, KC_J), MT(MOD_RSFT, KC_K), MT(MOD_LALT, KC_L), MT(MOD_RGUI, KC_SCLN), KC_QUOT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSPC, KC_DOWN, KC_UP, KC_LBRC, KC_RBRC, KC_RGUI, KC_RCTL, KC_PGUP, KC_PGDN, KC_ENT, KC_SPC)
  //TODO make it so that if you hold the real shift button, it activates a layer that ignores the bottom row shift buttons
	[_BASE] = LAYOUT(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_LSPO, MT(MOD_LGUI, KC_Z), MT(MOD_LALT, KC_X), MT(MOD_LSFT, KC_C), MT(MOD_LCTL, KC_V), KC_B, KC_GRV, KC_INS, KC_LEFT, KC_RGHT, KC_RGUI, KC_LALT, KC_HOME, KC_BSPC, LT(_MOUSE, KC_DEL), KC_END, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_SLCK, KC_PAUS, KC_NO, RESET, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_N, MT(MOD_RCTL, KC_M), MT(MOD_RSFT, KC_COMM), MT(MOD_LALT, KC_DOT), MT(MOD_RGUI, KC_SLSH), KC_RSPC, KC_DOWN, KC_UP, KC_LBRC, KC_RBRC, KC_RGUI, KC_RCTL, KC_PGUP, KC_PGDN, LT(_MOUSE, KC_ENT), KC_SPC),
	[_MOUSE] = LAYOUT(KC_ESC, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, RESET, KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_RSPC, MT(MOD_LGUI, KC_Z), MT(MOD_LALT, KC_X), MT(MOD_LSFT, KC_C), MT(MOD_LCTL, KC_V), KC_B, KC_GRV, KC_INS, KC_LEFT, KC_RGHT, KC_RGUI, KC_LALT, KC_HOME, KC_BSPC, LT(_MOUSE, KC_SPC), KC_END, KC_F9, KC_F10, KC_F11, KC_F12, KC_PSCR, KC_SLCK, KC_PAUS, KC_NO, RESET, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, U_RDO, U_PST, U_CPY, U_CUT, U_UND, KC_BTN3, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_BTN1, KC_BTN2, KC_WH_L, KC_WH_D, KC_WH_U, KC_WH_R, MT(MOD_RGUI, KC_SLSH), KC_BTN3, KC_DOWN, KC_UP, KC_LBRC, KC_RBRC, KC_RGUI, KC_RCTL, KC_PGUP, KC_PGDN, KC_ENT, KC_SPC)
};


